"""Render maps and validate the canonical curriculum. Run from any directory."""
from pathlib import Path
import argparse
import heapq
import os
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / '.local-deps'))
import yaml

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('command', choices=['build', 'check'])
args = parser.parse_args()
model = yaml.safe_load((ROOT / 'curriculum.yaml').read_text(encoding='utf-8'))
assert model['schema_version'] == 1
domains = model['curriculum']
references = {r['id']:r for r in model.get('references',[])}
assert len(references)==len(model.get('references',[])), 'Duplicate reference ID'
for reference in references.values():
    assert reference['url'].startswith('https://') and reference['title'].strip()
nodes, topics, owners = {}, {}, {}

def register(n):
    assert re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', n['id']), n['id']
    assert n['id'] not in nodes, f"Duplicate ID: {n['id']}"
    assert n['title'].strip()
    nodes[n['id']] = n

def ordered(items):
    ranks = [x['order'] for x in items]
    assert ranks == sorted(set(ranks)), 'Orders must be unique and increasing among siblings'

ordered(domains)
for d in domains:
    register(d)
    assert all(ref in references for ref in d.get('references',[])), d['id']
    ordered(d['subjects'])
    for s in d['subjects']:
        register(s)
        ordered(s['topics'])
        for t in s['topics']:
            register(t)
            assert t['concepts'], t['id']
            topics[t['id']] = t
            owners[t['id']] = d

edges = []
for d in domains:
    assert all(p in topics for p in d['prerequisites']), d['id']
for t in topics.values():
    for key in ['prerequisites','related','implements']:
        refs = t.get(key, [])
        assert len(refs) == len(set(refs)), (t['id'],key)
        assert all(p in topics and p != t['id'] for p in refs), (t['id'],key)
    edges.extend((p,t['id']) for p in t['prerequisites'])

successors = {id:[] for id in topics}
indegree = {id:0 for id in topics}
rank = {id:i for i,id in enumerate(topics)}
for a,b in edges:
    successors[a].append(b)
    indegree[b] += 1
ready = [(rank[id],id) for id in topics if not indegree[id]]
heapq.heapify(ready)
sequence = []
while ready:
    _,id = heapq.heappop(ready)
    sequence.append(id)
    for child in successors[id]:
        indegree[child] -= 1
        if indegree[child] == 0:
            heapq.heappush(ready,(rank[child],child))
assert len(sequence) == len(topics), f"Prerequisite cycle: {[id for id,n in indegree.items() if n]}"

def target(id):
    return topics[id].get('note', owners[id]['path']+'#'+id)

def link(id, source, wiki=True):
    destination = target(id)
    file, sep, anchor = destination.partition('#')
    relative = os.path.relpath(ROOT/file,(ROOT/source).parent).replace('\\','/')
    title = topics[id]['title']
    md = f'[{title}]({relative}{sep}{anchor})'
    wikidest = file.removesuffix('.md')+sep+(title if sep else '')
    return f'[[{wikidest}|{title}]] · {md}' if wiki else md

def refs(ids, source):
    return '; '.join(link(id,source) for id in ids) or 'None — entry concept.'

def diagram(selected):
    ids = list(dict.fromkeys(id for pair in selected for id in pair))
    names = {id:f'n{i}' for i,id in enumerate(ids)}
    return '\n'.join(['```mermaid','flowchart TD'] + [f'    {names[id]}["{topics[id]["title"]}"]' for id in ids] + [f'    {names[a]} --> {names[b]}' for a,b in selected] + ['```'])

outputs = {}
dependency_model = dict(schema_version=1,direction='prerequisite -> dependent',source='curriculum.yaml topic prerequisites; domain entry prerequisites are summaries, not inherited edges',dependencies=[dict(**{'from':a},to=b) for a,b in edges])
outputs['dependencies.yaml'] = '# Generated by scripts/curriculum.py build; edit curriculum.yaml instead.\n'+yaml.safe_dump(dependency_model,sort_keys=False)

for d in domains:
    path = d['path']
    local = [id for id in sequence if owners[id]['id']==d['id']]
    lines = [f'# {d["title"]}', '', '<!-- Generated map: edit curriculum.yaml, then run scripts/curriculum.py build. -->','', '[Master curriculum](../CURRICULUM.md) · [Model and editing guide](../CONTRIBUTING.md)', '', '## Purpose','',d['purpose'],'','## Prerequisites','',refs(d['prerequisites'],path),'','These orient entry into the domain; each topic below has its own requirements. They are not inherited gates.','','## Recommended Learning Order','','This is one dependency-compatible reading order. External prerequisites can be learned in parallel; numbering is guidance, not a completion checklist.','']
    lines.extend(f'{i}. {link(id,path,False)}' for i,id in enumerate(local,1))
    lines.extend(['','## Major Areas',''])
    for s in d['subjects']:
        lines.extend([f'### {s["title"]}',''])
        for t in s['topics']:
            id=t['id']
            lines.extend([f'<a id="{id}"></a>',f'#### {t["title"]}','',f'**Concepts:** {"; ".join(t["concepts"])}.', '',f'**Prerequisites:** {refs(t["prerequisites"],path)}',''])
            if t.get('note'): lines.extend([f'**Topic note:** {link(id,path)}',''])
            if t.get('implements'): lines.extend([f'**Implements / applies:** {refs(t["implements"],path)}',''])
            if t.get('related'): lines.extend([f'**Related:** {refs(t["related"],path)}',''])
    relevant=[(a,b) for a,b in edges if b in local]
    selected=[]
    seen=set()
    for pair in sorted(relevant,key=lambda p:(p[0] not in local,rank[p[1]],rank[p[0]])):
        if len(seen|set(pair))<=8 and len(selected)<8:
            selected.append(pair); seen.update(pair)
    if selected: lines.extend(['## Dependency Sketch','','Selected direct prerequisite edges, not the entire domain graph. Arrows mean “learn before”.','',diagram(selected),''])
    downstream=list(dict.fromkeys(b for a,b in edges if a in local and b not in local))
    lines.extend(['## Leads To','',refs(downstream,path) if downstream else 'Specialize further according to real systems and learning needs.',''])
    if d.get('references'):
        lines.extend(['## Reference Roadmaps','','Use these for coverage and further exploration; the prerequisite relationships here are curated independently.',''])
        lines.extend(f'- [{references[ref]["title"]}]({references[ref]["url"]})' for ref in d['references'])
        lines.extend(['','[Reference review and scope decisions](../references/roadmap-sh.md)',''])
    outputs[path]='\n'.join(lines)

phases = [
 ('0 — Foundations',['foundations','computer-systems','operating-systems']),
 ('1 — Systems',['linux','networking']),
 ('2 — Software and Automation',['programming','software-engineering','git','databases']),
 ('3 — Infrastructure',['containers','cloud','aws','infrastructure-as-code','configuration-management']),
 ('4 — Platforms and Delivery',['kubernetes','ci-cd','gitops']),
 ('5 — Production Engineering',['observability','security','distributed-systems','sre','system-design','production-operations']),
 ('6 — Specialization',['advanced'])]
lines=['# Master Curriculum','','<!-- Generated from curriculum.yaml; do not edit this map directly. -->','','Phases are a reading guide, not prerequisite gates. Start security with system access, telemetry with your first programs, and reliability with your first cloud designs. Linux and networking can develop in parallel. Consult topic prerequisites before choosing a branch.','','Each subject groups meaningful topics; the indented concept lists describe their scope. Most topics initially live in their domain map. Six representative topics have detailed notes.','']
for title,ids in phases:
    lines.extend([f'## Phase {title}',''])
    for id in ids:
        d=next(d for d in domains if d['id']==id)
        lines.extend([f'### [{d["title"]}]({d["path"]})','',d['purpose'],''])
        for s in d['subjects']:
            lines.extend([f'#### {s["title"]}',''])
            for t in s['topics']:
                lines.append(f'- {link(t["id"],"CURRICULUM.md",False)} — {"; ".join(t["concepts"])}.')
            lines.append('')
lines.extend(['## Cross-domain Dependency Sketches','','These show selected direct prerequisites. Related and implementation links do not imply a learning gate.',''])
for title,pairs in [
 ('Systems to orchestration',[('os-fundamentals','processes-threads'),('processes-threads','linux-processes'),('linux-processes','container-fundamentals'),('container-fundamentals','kubernetes-architecture'),('docker-networking','kubernetes-architecture')]),
 ('Addressing to service networking',[('ip-addressing','subnetting'),('subnetting','routing'),('routing','kubernetes-networking'),('dns','kubernetes-networking'),('kubernetes-networking','kubernetes-services')]),
 ('Declarative delivery',[('desired-state','infrastructure-as-code-principles'),('infrastructure-as-code-principles','terraform-configuration'),('terraform-configuration','terraform-state'),('desired-state','gitops-principles'),('gitops-principles','argo-cd')]),
 ('Reliability to operations',[('telemetry','reliability-objectives'),('reliability-fundamentals','reliability-objectives'),('reliability-objectives','alerting-investigation'),('alerting-investigation','incident-management'),('operational-readiness','incident-management')])]:
    assert all(pair in edges for pair in pairs)
    lines.extend([f'### {title}','',diagram(pairs),''])
outputs['CURRICULUM.md']='\n'.join(lines)

for name,content in outputs.items():
    path=ROOT/name
    if args.command=='build':
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(content,encoding='utf-8')
    else:
        assert path.exists() and path.read_text(encoding='utf-8')==content, f'Stale generated file: {name}'

if args.command=='check':
    for t in topics.values():
        if 'note' in t:
            note=ROOT/t['note']
            assert note.exists(),f'Missing note: {note}'
            front=note.read_text(encoding='utf-8').split('---',2)
            assert len(front)==3 and yaml.safe_load(front[1])['id']==t['id']
            assert '## Prerequisites' in front[2]
            for pre in t['prerequisites']:
                file,sep,anchor=target(pre).partition('#')
                wiki_anchor=topics[pre]['title'] if sep else ''
                assert f'[[{file.removesuffix(".md")}{sep}{wiki_anchor}|' in front[2],f'Missing note prerequisite {pre} in {t["id"]}'
    for path in ROOT.rglob('*.md'):
        if any(part.startswith('.') for part in path.relative_to(ROOT).parts): continue
        text=path.read_text(encoding='utf-8')
        text=re.sub(r'```.*?```','',text,flags=re.S)
        text=re.sub(r'`[^`\n]*`','',text)
        destinations=[]
        for dest in re.findall(r'(?<!!)\[[^\]\n]+\]\(([^)]+)\)',text):
            if not re.match(r'\w+://',dest): destinations.append((path.parent,dest))
        for dest in re.findall(r'\[\[([^\]|]+)(?:\|[^\]]+)?\]\]',text):
            file,sep,anchor=dest.partition('#')
            destinations.append((ROOT,file+'.md'+sep+anchor))
        for base,dest in destinations:
            file,sep,anchor=dest.partition('#')
            targetpath=(base/file).resolve()
            assert targetpath.is_relative_to(ROOT) and targetpath.exists(),f'Broken link in {path}: {dest}'
            if sep:
                body=targetpath.read_text(encoding='utf-8')
                anchors=set(re.findall(r'<a id="([^"]+)"',body))
                headings=re.findall(r'^#+ (.+)$',body,re.M)
                anchors.update(headings)
                anchors.update(re.sub(r'[^\w\- ]','',h.lower()).replace(' ','-') for h in headings)
                assert anchor in anchors, f'Broken anchor in {path}: {dest}'
    print(f'Validated {len(domains)} domains, {len(topics)} topics, {len(edges)} prerequisite edges; graph acyclic; generated maps, note prerequisites, and local links consistent.')
else:
    print(f'Generated {len(outputs)} maps and dependency files.')
